<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "flux_galleria"
 *
 * Auto generated by Extension Builder 2013-01-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Galleria picture and video gallery',
	'description' => 'Includes Javascript based Galleria extension as a fluid content element. Based on flux and fluidcontent.',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
			'flux' => '5',
			'fluidcontent' => '2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>